// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reports.sql

package database

import (
	"context"
	"database/sql"
)

const searchReports = `-- name: SearchReports :many
SELECT id, reported_at, reported_by, reason FROM reports
WHERE reported_by LIKE $1 || '%'
`

func (q *Queries) SearchReports(ctx context.Context, dollar_1 sql.NullString) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, searchReports, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReportedAt,
			&i.ReportedBy,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
